services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Behat\Context\Shop\CartContext:
        public: true
        arguments:
            $productShowPage: '@sylius.behat.page.shop.product.show'
